#!/bin/sh
# ---
# Copyright (c) 2020 Alex Blewitt
#
# Released under the MIT License SPDX:MIT
# See LICENSE.txt for more information
# ---
# Updates ctags in a git directory
#
# Usage:
#
#   $(git rev-parse --git-dir)/hooks/ctags-update

set -euo pipefail

git_root="$(git rev-parse --show-toplevel)"

echo cd "${git_root}"
cd "${git_root}"

git_dir="$(git rev-parse --git-dir)"
tags="${git_dir}/tags"
tags_tmp="${tags}-$$"

# Clean up temporary file when finished
trap 'rm -f "${tags_tmp}"' EXIT
pwd
echo "$(dirname "$0")/ctags" --recurse --tag-relative -L - -f "${tags_tmp}"

# Pipe the list of files into ctags' input stream, and write to .git/tags
git ls-files | "$(dirname "$0")/ctags" --recurse --tag-relative -L - -f "${tags_tmp}"

# Once complete, move the temporary tags file into place
mv -f "${tags_tmp}" "${tags}"
